# Generated by Django 2.1.7 on 2019-03-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
