# Generated by Django 2.1.7 on 2019-03-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20190320_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/item/', verbose_name='подпись'),
        ),
    ]
