# Generated by Django 2.1.7 on 2019-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20190323_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(4), to='catalogue.Category'),
        ),
    ]
